// tslint:disable
/**
 * Global Attributes Client API Specification
 * API to retrieve global attributes for requested parameters from client
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    GetCountriesListResponse,
} from '../models';

export interface GetCountriesListRequest {
    xTxnId?: string;
}

/**
 * no description
 */
export class GlobalAttributesApi extends BaseAPI {

    /**
     * Returns all countries list from master
     * Get all countries list
     */
    getCountriesList({ xTxnId }: GetCountriesListRequest): Observable<GetCountriesListResponse>
    getCountriesList({ xTxnId }: GetCountriesListRequest, opts?: OperationOpts): Observable<AjaxResponse<GetCountriesListResponse>>
    getCountriesList({ xTxnId }: GetCountriesListRequest, opts?: OperationOpts): Observable<GetCountriesListResponse | AjaxResponse<GetCountriesListResponse>> {

        const headers: HttpHeaders = {
            ...(xTxnId != null ? { 'x-txn-id': String(xTxnId) } : undefined),
        };

        return this.request<GetCountriesListResponse>({
            url: '/client-api/v1/configuration/countries',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
