// tslint:disable
/**
 * Global Attributes Client API Specification
 * API to retrieve global attributes for requested parameters from client
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CountryObject
 */
export interface CountryObject {
    /**
     * Country Name
     * @type {string}
     * @memberof CountryObject
     */
    countryName: string;
    /**
     * Country ISO Code
     * @type {string}
     * @memberof CountryObject
     */
    countryISOCode: string;
    /**
     * Country Code
     * @type {number}
     * @memberof CountryObject
     */
    countryCode: number;
}
